const AppData = {
  about: {
    firstName: "Sanjeet",
    lastName: "Kumar",
    mobileNo: "9445165233",
    email: "isanjeet09@gmail.com",
    workStarted: "08/01/2016",
    country: "India",
    location: "Bengaluru",
    linkedIn: "https://www.linkedin.com/in/isanjeet09",
    gitHub: "https://github.com/sanjeet05",
    whatsapp: "https://wa.me/919445165233",
  },
  experience: [
    {
      id: 107,
      name: "Alphastream.ai",
      url: "https://alphastream.ai/",
      role: "Sr. Full Stack Engineer",
      start_date: new Date("02/09/2026"), // mm/dd/yyyy
      end_date: new Date(""), // mm/dd/yyyy
      is_present: true,
      line_1: [
        "Working with NestJS, NodeJS, ExpressJS, MySql, DynamoDB, Redis, ReactJS, NextJS, GatsBy, Graphql, ES6, Docker, Webpack, NPM, Bootstrap, Html, CSS, Git - Transform raw deal data into real-time intelligence.",
      ],
      line_2: "",
      tags: [
        "Rest APIs",
        "Graphql",
        "MicroService",
        "NodeJS",
        "Docker",
        "MERN Stack",
        "AWS",
        "CI/CD Pipeline",
        "Jira",
      ],
    },
    {
      id: 106,
      name: "Twin Health",
      url: "https://ind.twinhealth.com/",
      role: "Sr. Full Stack Engineer",
      start_date: new Date("03/01/2021"), // mm/dd/yyyy
      end_date: new Date("10/30/2025"), // mm/dd/yyyy
      is_present: false,
      line_1: [
        "Developed and scaled a Whole Body Digital Twin AI platform focused on reversing Type 2 Diabetes and improving metabolic health outcomes.",
        "Led and mentored a team of engineers through code reviews, architectural guidance, and adoption of best practices.",
        "Collaborated with QA, Product, and cross-functional stakeholders to deliver stable, on-time releases.",
        "Designed and maintained a microservices-based architecture to support high availability and scalability.",
        "Built and managed CI/CD pipelines and containerized deployments using Docker and Kubernetes on AWS.",
        "Integrated Razorpay and WhatsApp Business APIs, improving payment success rates and user engagement.",
        "Optimized frontend performance, reducing page load times by <b>30%</b> and improving UI responsiveness.",
        "Used AI Copilot tools to accelerate development and improve code quality, refactoring, and test generation.",
      ],
      line_2: "",
      tags: [
        "Rest APIs",
        "Graphql",
        "MicroService",
        "NodeJS",
        "Docker",
        "MERN Stack",
        "AWS",
        "CI/CD Pipeline",
        "Jira",
      ],
    },
    {
      id: 105,
      name: "SWRM Labs",
      url: "https://www.linkedin.com/company/swrmlabs/",
      role: "Full Stack Engineer",
      start_date: new Date("10/06/2019"),
      end_date: new Date("03/20/2021"),
      is_present: false,
      line_1: [
        "Worked with NodeJS, ExpressJS, PostgreSQL, MongoDB, Redis, ReactJS, ES6, D3.JS, Webpack, NPM, Material-UI, Bootstrap, Semantic-UI, Html, CSS, Git to create blockchain powered products.",
        "Built web interfaces for Ethereum wallet integrations using Ether.js.",
        "Implemented real-time communication features using Socket.io.",
        "Automated build and deployment processes through CI/CD pipelines.",
        "Improved system reliability, reducing production errors by <b>25%</b>.",
      ],
      line_2: "",
      tags: [
        "Blockchain",
        "Web3.JS",
        "IPFS",
        "Docker",
        "Rest APIs",
        "MERN Stack",
        "MicroService",
        "AWS",
        "CI/CD Pipeline",
        "Jira",
      ],
    },
    {
      id: 104,
      name: "Qualitics",
      url: "https://www.linkedin.com/company/qualiticsusa/",
      role: "Full Stack Engineer",
      start_date: new Date("09/11/2018"),
      end_date: new Date("10/12/2019"),
      is_present: false,
      line_1: [
        "Worked with Python, NodeJS, ExpressJS, MongoDB, PostgreSQL, Redis, ReactJS, Redux, ES6, Webpack, NPM, Material-UI, Bootstrap, Git, Nginx, Docker, AWS, Rest API to create a testing platform.",
        "Developed backend services using Node.js, Python, and Flask.",
        "Implemented JWT-based authentication and authorization.",
        "Integrated PayPal payment gateway, improving transaction reliability.",
        "Built 30+ reusable UI components, improving development speed by <b>20%</b> using React.js.",
      ],
      line_2: "",
      tags: [
        "Rest APIs",
        "Python",
        "MongoDB",
        "ReactJS",
        "NodeJS",
        "AWS",
        "CI/CD Pipeline",
        "Jira",
      ],
    },
    {
      id: 103,
      name: "Zylotech - Acquired by Terminus",
      url: "https://www.linkedin.com/company/zylotech/",
      role: "Full Stack Developer",
      start_date: new Date("08/28/2017"),
      end_date: new Date("09/10/2018"),
      is_present: false,
      line_1: [
        "Worked on building for customer AI products, hands-on experience in end to end phase of software development life-cycle. Responsible for end-to-end product design and development of the base platform for the web platform.",
        "Developed REST APIs and integrated them with React.js frontends.",
        "Implemented role-based access control (RBAC) and multi-tenant authentication systems.",
        "Integrated AI-powered recommendation services.",
      ],
      line_2: "Stack Used: MERN Stack Framework - Python, NodeJS, ExpressJS, ElasticSearch, MongoDB, PostgreSQL, Redis, ReactJS, Redux, ES6, D3.JS, Webpack, NPM, Material-UI, Semantic-UI, Bootstrap, Git, Nginx, Docker, AWS, Rest API.",
      tags: [
        "Rest APIs",
        "PostgreSQL",
        "ReactJS",
        "NodeJS",
        "ElasticSearch",
        "MERN Stack",
      ],
    },
    {
      id: 102,
      name: "SmartWinnr",
      url: "https://www.smartwinnr.com/",
      role: "Software Engineer",
      start_date: new Date("08/21/2016"),
      end_date: new Date("08/25/2017"),
      is_present: false,
      line_1: [
        "Worked on building for next generation product, hands on experience in end to end phase of software development life-cycle. Responsible for end-to-end product design and development of the base platform for mobile and web platform.",
        "Developed hybrid mobile applications using Cordova and AngularJS.",
        "Built survey and quiz management platforms.",
        "Designed RESTful services and MongoDB data models.",
      ],
      line_2: "Stack Used: Mean Stack Framework (NodeJS, ExpressJS, AngularJS, MongoDB), Redis, D3.JS, REST, NPM, Bower, Gulp, Bootstrap, AdminLte, BlurAdmin, Ionic Framework, Cordova, SqLite, Android SDK, Html, CSS, Git.",
      tags: [
        "Rest APIs",
        "MongoDB",
        "AngularJS",
        "NodeJS",
        "ExpressJS",
        "MEAN Stack",
        "JSON",
        "Hybrid App",
      ],
    },
    // {
    //   id: 101,
    //   name: "Sense Infinity Technology",
    //   url: "",
    //   role: "Full Stack Developer as Intern",
    //   start_date: new Date("05/10/2016"),
    //   end_date: new Date("08/08/2016"),
    //   is_present: false,
    //   line_1: `Worked on building a cool product, which is an e-commerce engine
    //   for a vertical space. as a part of the core team to architect
    //   and develop the web platform for all business and operational
    //   needs of the startup.`,
    //   line_2: `Stack Used: Laravel Framework(PHP), MySql, AngularJS, Bootstrap,
    //   Html, CSS, Git.`,
    //   tags: ["Intern", "Rest APIs", "Laravel", "AngularJS", "Git"]
    // }
  ],
  education: [
    {
      id: 102,
      level: "master",
      college: "Pondicherry University",
      course: "Master of Computer Application (MCA)",
      start_date: new Date("07/03/2013"),
      end_date: new Date("05/10/2016"),
    },
    {
      id: 101,
      level: "graduation",
      college: "Kuvempu University",
      course: "Bachelor of Science (B.Sc)",
      start_date: new Date("07/10/2008"),
      end_date: new Date("09/28/2012"),
    },
  ],
};

export default AppData;
